# This is a basic workflow to help you get started with Actions

name: CreateBaseBranchingStructure

# Controls when the workflow will run
# Allows you to run this workflow manually from the Actions tab
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  createBranches:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    #declare variables
    env:
      HOTFIXEXISTS: false
      RELEASEEXISTS: false
      DEVELOPMENTEXISTS: false
      FEATUREEXISTS: false
  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        name: CheckoutRepoAndCompareBranches
         
          $url = "https://github.com/noffz-technologies/PRNumber-ABNumber-CustomerName-TesterType-ProjectName"
          $token = [System.Convert]::ToBase64String([System.Text.Encoding]::ASCII.GetBytes(":$(system.accesstoken))"))
          $response = Invoke-RestMethod -Uri $url -Headers @{Authorization = "Basic $token"} -Method Get  -ContentType application/json
  
          foreach ($Refname in §response.value.name)
          {
            if ($Refname -eq "refs/head/Hotfix")
            {
              $HOTFIXEXISTS = true
            }
            if ($Refname -eq "refs/head/Release")
            {
              $RELEASEEXISTS = true
            }
            if ($Refname -eq "refs/head/Development")
            {
              $DEVELOPMENTEXISTS = true
            }
            if ($Refname -eq "refs/head/Feature")
            {
              $FEATUREEXISTS = true
            }
          }
          
      - name: CreateHotfixBranch
        if: ${{ env.HOTFIXEXISTS == false }}      
        run: git branch Hotfix
        
      - name: CreateReleaseBranch
        if: ${{ env.RELEASEEXISTS == false }}
        run: git branch Release

      - name: CreateDevelopmentBranch
        if: ${{ env.DEVELOPMENTEXISTS == false }}
        run: git branch Development

      - name: CreateFeatureBranch
        if: ${{ env.FEATUREEXISTS == false }}
        run: git branch Feature
                 
      - name: CheckOutMain
        run: git checkout main
        
      - name: GitPush
        run: git push --all origin
